### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by mhadji05** [rotolonico/Firebase-Auth-with-Google-REST-API#1]
I add on FirebaseAuthHandler class my ApiKey  and
on GoogleAuthenticator class ClientId, ClientSecret
but when i press get google code i take 

![image](https://user-images.githubusercontent.com/22151801/69010093-7f93e580-0964-11ea-975e-24a0c1d33e70.png)

**Comment by mhadji05** [comment]
I think i know whats going wrong. i need to set ClientId, ClientSecret from google cloud. So i need to pay google for that? you can start with $300 but when you spent that you need to pay?

**Comment by mhadji05** [comment]
ok now i can get a token from browser but i cant sign in with this token

**Comment by mhadji05** [comment]
I think i undersand now. i did it but why cant see the gmail on my authentication and only see is "-"



![image](https://user-images.githubusercontent.com/22151801/69011261-6f363780-0971-11ea-8578-e53ef21d7b36.png)

**Comment by rotolonico** [comment]
Thanks for the report! The reason you can't see the email because I used a different scope in the repository than the one that I used in the tutorial (email). This issue has now been fixed!
