### ISSUE TITLE
auto Google-sign-in without user copy and paste code.

### ISSUE THREAD

**Issue by mhadji05** [rotolonico/Firebase-Auth-with-Google-REST-API#2]
Thanks for the Interesting tutorial!
I have a question for you. Is there a way to make auto Google-sign-in ? In similar applications they do it without user copy and paste some code.

**Comment by rotolonico** [comment]
I haven't checked lately, but I am pretty sure just authenticating with Google API is free!
Auto sign-in is possible with the Loopback IP address method, I just used the manual copy/paste method in the tutorial for simplicity... you can learn more about it [here](https://developers.google.com/identity/protocols/OAuth2InstalledApp#redirect-uri_loopback)!
I might do a video on this method in the future!
