### ISSUE TITLE
Project clean needed. README.md is not updated.

### ISSUE THREAD

**Issue by potitoaghilar** [rotolonico/Firebase-Auth-with-Google-REST-API#3]
Project need to be cleaned from unnecessary directories.
Consider downloading a gitignore from here: [https://www.gitignore.io/api/unity](https://www.gitignore.io/api/unity).

README.md needs to be update with minimal project information.

**Comment by rotolonico** [comment]
Whoops, completely forgot about that.
It's fixed now, thanks!
